pipeline {
    agent any

    stages {

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Restart Express App') {
            steps {
                sh '''
                pm2 restart express-app || pm2 start app.js --name express-app
                '''
            }
        }
    }
}
