pipeline {
    agent any

    stages {

        stage('Install Dependencies') {
            steps {
                dir('backend') {
                    sh '''
                    python3 -m venv venv || true
                    venv/bin/python -m pip install --upgrade pip
                    venv/bin/python -m pip install -r requirements.txt
                    '''
                }
            }
        }

        stage('Restart Flask App') {
            steps {
                dir('backend') {
                    sh '''
                    pm2 restart flask-app || pm2 start venv/bin/python --name flask-app -- app.py
                    '''
                }
            }
        }
    }
}
